version: '3'

services:
 # Use healthcheck to let backend know when the db is up.
  postgres:
    image: postgres:alpine
    container_name: postgres_marketplace_strapi_dev
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=strapitest
    ports:
      - "6500:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    restart: unless-stopped
    networks:
      - monorepo_network
    healthcheck:
      test: "exit 0"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container_marketplace_strapi_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    depends_on:
      - postgres
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - monorepo_network

volumes:
  postgres:

# Networks to be created to facilitate communication between containers
networks:
  monorepo_network:
    driver: bridge
